spring:
  application:
    name: currency exchange
  profiles:
    active: default
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: debug
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: on_trace_param
    include-message: always

exchangerate:
  clients: ${CLIENTS:http://localhost:8180,http://localhost:8280}

