spring:
  application:
    name: external client 2
  profiles:
    active: default
server:
  error:
    include-stacktrace: on_trace_param
    include-message: always
  port: ${PORT:8280}
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: debug


external:
  api:
    url: https://api.exchangerate-api.com